AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'hello-world-serverless

  Sample SAM Template for hello-world-serverless

  '
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://zxcaeqwegsdfsdf/fe25f4d709f0fa53014d1f9b8e02cb7b
      Handler: parser.sendMenuButton
      Runtime: nodejs14.x
      Environment:
        Variables:
          SLACK_URL: Hello World
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: post
    Metadata:
      SamResourceId: HelloWorldFunction
  checkResult:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://zxcaeqwegsdfsdf/fe25f4d709f0fa53014d1f9b8e02cb7b
      Handler: pars.checkResult
      Runtime: nodejs14.x
      Environment:
        Variables:
          SLACK_URL:
            Ref: apiGateway
      Architectures:
      - x86_64
    Metadata:
      SamResourceId: checkResult
  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: A test API
      Name: apiGateway
    Metadata:
      SamResourceId: apiGateway
  PostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:
        Ref: apiGateway
      ResourceId:
        Fn::GetAtt:
        - apiGateway
        - RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${checkResult.Arn}/invocations
    Metadata:
      SamResourceId: PostMethod
  CallBackDeploymentApi:
    DependsOn: PostMethod
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: apiGateway
      Description: Automatically created by the RestApi construct
    Metadata:
      SamResourceId: CallBackDeploymentApi
  CallbackStageApi:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: apiGateway
      DeploymentId:
        Ref: CallBackDeploymentApi
      StageName: prod
    Metadata:
      SamResourceId: CallbackStageApi
  apiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - checkResult
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ':'
          - Ref: AWS::AccountId
          - ':'
          - Ref: apiGateway
          - /
          - Ref: CallbackStageApi
    Metadata:
      SamResourceId: apiPermission
Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionRole
      - Arn
Metadata:
  AWS::ServerlessRepo::Application:
    Name: slackBotChuiko2
    Description: slack bot
    Author: nazariichuiko
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://zxcaeqwegsdfsdf/86d3f3a95c324c9479bd8986968f4327
    ReadmeUrl: s3://zxcaeqwegsdfsdf/1caf7e41ecdd075c014b0860d132a8ac
    Labels:
    - tests
    HomePageUrl: https://github.com/nazarChuiko/hello-world
    SemanticVersion: '0.2.9'
    SourceCodeUrl: https://github.com/nazarChuiko/hello-world
